* Dotfile Configurations

**** Bashrc
     My bashrc config complete with a bunch of useful aliases and color prompt setup. There are numerous files involved.
- [[./bashrc][See files]]

**** Emacs
     My emacs config which is currently set up for org as well as Javascript & Python development.
- [[./emacs][Files & Readme]]
- [[./emacs/.emacs][Config File]]

**** i3 Window Manager
     My config files for i3wm. Includes a custom lock screen and more. There are some dependencies, though. You can see them as executables in the config file. Uses i3blocks for status bar.
- [[./i3][Files & Readme]]

**** Tmux
     My tmux configuration with some keybind changes (for Vim-like navigation) as well as theming.
- [[./tmux][Files & Readme]]
- [[./tmux/.tmux.conf][Config File]]

**** Vim
     A vim setup for JS and Python development as well as a ton of themes. Packages are handled with vundle.
- [[./vim][Files & Readme]]
- [[./vim/.vimrc][Config File]]

** TODO Things that need fixing in this repo [1/4]
   - [ ] Finish updating the documentation. There are inaccuracies.
   - [ ] Update Tmux documentation (no more vim directional navigation)
   - [X] Convert .emacs into an org config loader
