#! /usr/bin/bash

layouts=/home/trevdev/.dotfiles/scripts/layouts
hdmi_plugged=$(xrandr|grep ' connected'|grep 'HDMI'|awk '{print $1}')

if [ -z "$hdmi_plugged" ];
then
  exec "$layouts/laptop";
else
  exec "$layouts/monitor_plugged_in";
fi
