export GEM_HOME=$HOME/.gem
export GOPATH=$HOME/Projects/Go
export GOBIN=$HOME/Projects/Go/bin
export BROWSER=/usr/bin/firefox
export EDITOR=/usr/bin/nvim
export MAIL=$HOME/Mail/mailfence
export QT_STYLE_OVERRIDE=gtk

USERBINS=~/.local/bin
NPM=~/.local/npm/bin
RUBY=$(ruby -e 'print Gem.user_dir')/bin
GO=$GOPATH/bin
PYTHON=~/.local/lib/python3.8
CARGO=~/.cargo/bin
COMPOSER=$HOME/.config/composer/vendor/bin

export PATH=$USERBINS:$NPM:$RUBY:$GO:$PYTHON:$CARGO:$COMPOSER:$PATH

alias xflock4='light-locker-command -l'

alias xcp="pwd|xclip"
alias xcd='cd $(xclip -o)'
alias what="pacman -Qi"
alias composer7="php7 /usr/bin/composer"
alias sysstart="sudo systemctl start"
alias sysstop="sudo systemctl stop"
alias sysenable="sudo systemctl enable"
alias sysdisable="sudo systemctl disable"
alias sysrestart="sudo systemctl restart"
alias sysstatus="sudo systemctl status"
alias rebooty="sudo systemctl reboot"
alias merge="/opt/sublime_merge/sublime_merge"
alias start="/home/trevdev/.dotfiles/scripts/sessions.sh"

export BORG_PASSPHRASE=$(pass Borg/Local\ Repokey)
